### ISSUE TITLE
Posting `/packit rebuild-failed` comment in GH PR re-triggers all builds

### ISSUE THREAD

**Issue by thozza** [packit/packit-service#1422] opened 2022-03-29 06:18 UTC
Based on the PackIt documentation, adding `/packit rebuild-failed` comment to a PR should re-trigger only failed builds. However in reality, the comment results in also passed builds to be re-triggered.

In addition, the screenshot on https://packit.dev/docs/packit-service/#how-to-re-trigger-packit-service-actions-in-your-pull-request shows `Re-run` "button" next to a failed build, however there is no such "button" shown next to failed builds on GitHub...

**Comment by mfocko** [comment] 2022-03-29 06:23
Closing as duplicate of #1375

**Closed by mfocko** 2022-03-29 06:23 UTC

**Comment by lbarcziova** [comment] 2022-03-29 07:03
> In addition, the screenshot on https://packit.dev/docs/packit-service/#how-to-re-trigger-packit-service-actions-in-your-pull-request shows Re-run "button" next to a failed build, however there is no such "button" shown next to failed builds on GitHub...

Do you have write access to the repository where you checked this? (For being able to rerun job via `Re-run` button this is needed.)

**Comment by thozza** [comment] 2022-03-29 07:06
> Do you have write access to the repository where you checked this? (For being able to rerun job via `Re-run` button this is needed.)

Not sure what do you mean by "write access". I can push to that repository, except for protected branches, merge PRs and re-run all Github actions....

**Comment by thozza** [comment] 2022-03-29 07:14
@lbarcziova I was able to get to a view, in which I can see the "Re-run" button. I was expecting to see it on the default PR tab in the table of all checks. However it is shown only in the "Checks" tab of the PR... Sorry for the noise 😕 

I should learn to read the documentation more carefully 🙄

**Comment by lbarcziova** [comment] 2022-03-29 07:19
> @lbarcziova I was able to get to a view, in which I can see the "Re-run" button. I was expecting to see it on the default PR tab >in the table of all checks. However it is shown only in the "Checks" tab of the PR... Sorry for the noise confused
>
>I should learn to read the documentation more carefully roll_eyes

Sure, no problem, thanks for letting us know!
