### ISSUE TITLE
Stray comment on a PR commit after force-push

### ISSUE THREAD

**Issue by mrc0mmand** [packit/packit-service#965] opened 2021-02-09 19:01 UTC
Today I noticed in one of our PRs that after a force-push one of the Packit jobs commented on the old version of the last commit, even though the comments should be disabled (by default):

PR in question: https://github.com/systemd/systemd/pull/17823
Commit comment: https://github.com/systemd/systemd/commit/aea34d1f9d5da08aa8ba9c6f7e151a2d8f170e47#commitcomment-46936427
Packit job: https://prod.packit.dev/copr-build/80382

Screenshot, in case the commit got gc'ed:
![image](https://user-images.githubusercontent.com/679338/107413865-939ba800-6b11-11eb-9d2f-9b70fe54609a.png)

**Comment by mfocko** [comment] 2021-02-09 20:01
Thanks for your report.

I glanced through the PR
- there's an open issue #5 for canceling running jobs if any changes occur, e.g. push or force-push
  i.e. the build for the commit has been already running by the time of force-push
- between the `i386` and `x64/arch64` is 12-minute gap and since we're talking about github there shouldn't be a permission problem
  lately I've seen multiple 500s from GitHub among the uncaught exceptions, so it could be reason for this comment
- there might be a slight confusion regarding comments
  - commit comment is used as fallback for commit statuses (we agreed on posting the comment instead of letting the commit status hang, as it does for the i386 in said commit)
  - we also comment on PR or commit in case there is a problem with COPR config or permissions (iirc in case of packit configuration we create issue)
  - disabled comments are the ones announcing successful copr build, like [this one](https://github.com/packit/ogr/pull/497#issuecomment-734732607)

imo duplicate of #5, @lachmanfrantisek should probably up the priority :)

**Comment by mrc0mmand** [comment] 2021-02-09 20:18
>     * there might be a slight confusion regarding comments
>       
>       * commit comment is used as fallback for commit statuses (we agreed on posting the comment instead of letting the commit status hang, as it does for the i386 in said commit)
>       * we also comment on PR or commit in case there is a problem with COPR config or permissions (iirc in case of packit configuration we create issue)

Ah, didn't know about these cases, now the Packit commit makes sense.

> imo duplicate of #5, @lachmanfrantisek should probably up the priority :)

In that case this indeed looks like a duplicate of #5, thanks a lot for the explanation! Feel free to close this issue then :)

**Comment by lachmanfrantisek** [comment] 2021-02-10 07:51
@mfocko Thanks for the detailed description.

@mrc0mmand thanks for letting us know.

Let's close this then.

**Closed by lachmanfrantisek** 2021-02-10 07:51 UTC
