### ISSUE TITLE
Handle hard time limits on tasks

### ISSUE THREAD

**Issue by nforro** [packit/packit-service#2290] opened 2023-12-20 19:22 UTC
A Celery task is killed after a timeout which is [900 seconds](https://github.com/packit/packit-service/blob/44e914f52a2b1a828e6bfb1386220681be608b8f/packit_service/celery_config.py#L39). If that happens, job statuses are no longer updated (so they usually stay in pending/running for good) and logs can be lost (for example logs from SRPM build in Sandcastle). Ideally in such case job status should be set to failed and logs preserved, if possible.

**Comment by lbarcziova** [comment] 2024-01-18 11:06
So Celery enables to configure also [soft_time_limit](https://docs.celeryq.dev/en/stable/userguide/configuration.html#std-setting-task_soft_time_limit), that can be set to a little bit lower value than the hard time limit, that raises an exception, so that some cleanup can be done. But as for setting the logs and status, I still think this would be quite complicated to implement as the exception is raised from the task itself so we do not know the stage of the task when the exc happened.
I would be probably more inclined to handling the root causes of this issue separately - as for downstream jobs, this should not be happening anymore after implementing packit/packit#2186 ( CC @nforro ) - looking into [the related Sentry issue](https://red-hat-it.sentry.io/issues/4395723769/events/1a15b8912ecd43d8bbeadf2376702145/) and its occurrences.

So this now [happens for `process_message`](https://red-hat-it.sentry.io/issues/4323136874/?environment=prod&project=1767823&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=4&utc=true), where setting the status/logs doesn't really apply (when I checked the occurrences, these tasks get blocked in early stages, so the effect in the end is no feedback for user at all for some action - e.g. currently for events from `gitlab.gnome.org`) . Here I would maybe suggest for `process_message` to lower the hard time limit as there are no possible `actions` running and no time-demanding things should happen.

**Comment by nforro** [comment] 2024-01-30 14:47
> Here I would maybe suggest for `process_message` to lower the hard time limit as there are no possible `actions` running and no time-demanding things should happen.

Sounds good to me (if there is a way to configure the limit per task type).

Otherwise I think this issue can be closed in favor of https://github.com/packit/packit-service/issues/2323.

**Comment by lbarcziova** [comment] 2024-02-02 11:28
I implemented both #2323 and lowering the limits in #2326, therefore closing this one.

**Closed by lbarcziova** 2024-02-02 11:28 UTC
Labels: complexity/single-task, impact/high, area/general, gain/high, kind/internal
