### ISSUE TITLE
Missing status report when multiple copr_build targets

### ISSUE THREAD

**Issue by jkonecny12** [packit/packit-service#1058] opened 2021-04-20 12:08 UTC
Hi, I have packit configuration with 2 `copr_build`s both triggered by the `commit` trigger. Seems they are working correctly but the status reporting did not.

You can see that in [this commit](https://github.com/rhinstaller/dasbus/commit/9672512ba1a7ceeab68558fa0fb3171a0df254cd) both builds seems to work correctly but status reported there is missing for `fedora-latest` job and ELN is still in progress based on the status.

![Screenshot from 2021-04-20 13-29-11](https://user-images.githubusercontent.com/1643889/115388669-6ee04280-a1dc-11eb-86df-9a8e358fe920.png)

This is the [packit config](https://github.com/rhinstaller/dasbus/blob/master/.packit.yaml.

**Comment by lachmanfrantisek** [comment] 2021-04-22 09:15
Hi @jkonecny12 !

I am really sorry about that but can't say now what is the cause. Someone from the team needs to take a look.

Some observation:
* There are two jobs defined for the same trigger and job type.
* There are `fedora-rawhide` and `fedora-eln` defined in one job and `fedora-latest` in the second one.
    * `fedora-rawhide` is correct
    * `fedora-eln` is missing the success state
    * `fedora-latest` is not present
* This is not a flake. It occurred two times in a row.

**Comment by jkonecny12** [comment] 2021-04-23 10:26
Np, the builds are fine so it's just a 'cosmetic' issue. Thanks for looking into that!

**Comment by lbarcziova** [comment] 2021-05-03 11:41
So the problem here is not about having 2 jobs defined for the same trigger and job type, but about the `fedora-latest` target, we do not process it right (fix [here](https://github.com/packit/packit/pull/1222)), therefore the result set of chroots is empty. Since the project already exists with the wanted target, the build is run, but neither reporting nor storing info in DB is happening. 
```
[2021-05-03 11:10:39,538: INFO/ForkPoolWorker-1] Trying to get @rhinstaller/Anaconda-devel Copr project. The project will be created if it does not exist.
[2021-05-03 11:10:39,837: INFO/ForkPoolWorker-1] Updating copr project '@rhinstaller/Anaconda-devel'
[2021-05-03 11:10:39,837: DEBUG/ForkPoolWorker-1] chroots: ['fedora-34-x86_64'] -> []
[2021-05-03 11:10:39,837: DEBUG/ForkPoolWorker-1] Copr edit arguments: {'chroots': []}
[2021-05-03 11:10:40,618: INFO/ForkPoolWorker-1] Build targets: {'d-x86_64', '--x86_64', 'r-x86_64', 'a-x86_64', '3-x86_64', 'f-x86_64', 'o-x86_64', 'e-x86_64', '4-x86_64'} 
...
[2021-05-03 11:10:40,618: INFO/ForkPoolWorker-1] Result set: set()

```

**Comment by lachmanfrantisek** [comment] 2021-05-03 12:22
@lbarcziova Well spotted! I've just approved the fix. Thanks!

**Comment by lbarcziova** [comment] 2021-05-04 07:15
So `fedora-latest` should work now (currently only in staging https://github.com/packit/hello-world/pull/331), it will be in production next Monday. Regarding the `fedora-eln` missing the success state, I assume this was probably just a flake, since newer commits have it set correctly. We could maybe improve our babysitting task if this will occur more often. For now, I am closing this issue.

**Closed by lbarcziova** 2021-05-04 07:15 UTC
Labels: bug
