### ISSUE TITLE
Unexpected username and e-mail in a changelog entry generated by propose_downstream job

### ISSUE THREAD

**Issue by nforro** [packit/packit-service#793] opened 2020-08-28 14:59 UTC
See for example [here](https://src.fedoraproject.org/rpms/rebase-helper/blob/master/f/rebase-helper.spec#_104).

`rebase-helper <rebase-helper@localhost.local>` are fallback values used by rebase-helper in case it's not possible to obtain the proper values from git configuration (i.e. `git config --get user.name` and `git config --get user.email` fail).

**Comment by jpopelka** [comment] 2020-08-31 16:24
hmm, the image looks OK to me:
```
$ docker run -ti --rm usercont/packit-service-worker:prod git config -l
user.name=Packit Service
user.email=user-cont-team+packit-service@redhat.com
```

**Comment by TomasTomecek** [comment] 2020-09-01 07:26
...but sandcastle doesn't have any

```
$ docker run -ti --rm usercont/sandcastle:prod git config --get user.name
$ echo $?
1
```

**Comment by jpopelka** [comment] 2020-09-01 08:53
I thought we use sandcastle only to build SRPM.

**Comment by lachmanfrantisek** [comment] 2020-09-01 10:35
> ...but sandcastle doesn't have any

Can we move this issue to sandcastle then?

**Comment by TomasTomecek** [comment] 2020-09-01 11:51
sandcastle is being used in multiple places and it seems bumpspec is executed in sandcastle

this definitely needs some investigation

anyway, @nforro this is great for you, your project is getting the credit :))

**Comment by lachmanfrantisek** [comment] 2020-09-30 06:42
ping sync2jira

**Comment by lbarcziova** [comment] 2020-10-06 10:51
Some more investigation:

- updating of the changelog [is not happening](https://github.com/packit/packit/blob/b531c63eac475c4909d51aa3c4cf636c78ef6c77/packit/specfile.py#L63) in sandcastle

- the commits in which the changelog entries have these default values have the names in `Signed off` section set correctly, but not the email (should be `user-cont-team+packit-service@redhat.com`):
` Signed-off-by: Packit Service <packit@packit-worker-2.packit-worker.packit-prod.svc.cluster.local> `
` Signed-off-by: Packit Service <packit@packit-worker-1.packit-worker.packit-prod.svc.cluster.local>` (haven't found record with worker-0)

-  happened in that time in other projects too  - https://src.fedoraproject.org/rpms/python-ogr/blob/f32/f/python-ogr.spec#_58, https://src.fedoraproject.org/rpms/packit/blob/f32/f/packit.spec#_84

**Comment by TomasTomecek** [comment] 2020-10-07 14:21
what does rpmdev-packager print?
```
$ rpmdev-packager                                                                                                                                
Tomas Tomecek <ttomecek@redhat.com>
```

**Comment by lbarcziova** [comment] 2020-10-07 15:24
In workers:
```
$ rpmdev-packager
id: cannot find name for user ID ...
Packit Service <user-cont-team+packit-service@redhat.com>
```
:thinking: 
Anyway, when updating changelog, the name and email should be obtained from [git config command](https://github.com/rebase-helper/rebase-helper/blob/31f8cfdd65a568eab4cf646c48dd78721e40cd0a/rebasehelper/helpers/git_helper.py#L49).

**Comment by TomasTomecek** [comment] 2020-10-08 08:28
It seems that we are using rebase-helper to update the changelog:
```python
    def update_changelog_in_spec(self, changelog_entry):
        if hasattr(self, "update_changelog"):
            # new rebase-helper
            self.update_changelog(changelog_entry)
```

So could the issue be in rebase-helper itself? We should investigate how it obtains the username and email.

**Comment by nforro** [comment] 2020-10-08 08:34
> So could the issue be in rebase-helper itself? We should investigate how it obtains the username and email.

As mentioned in the first post, rebase-helper just calls `git config --get user.name` and `git config --get user.email` (using [GitPython](https://github.com/gitpython-developers/GitPython), but that shouldn't matter).

**Comment by lbarcziova** [comment] 2020-10-08 09:27
>It seems that we are using rebase-helper to update the changelog

Yes, I was checking the method calls, that's how I came to the rebase-helper code which I linked in the comment above.

 > So could the issue be in rebase-helper itself? We should investigate how it obtains the username and email.

I don't think so, as it was said, it just uses GitPython methods.


`<packit@packit-worker-2.packit-worker.packit-prod.svc.cluster.local> ` but these emails in Signed-off are weird as well.

**Comment by lbarcziova** [comment] 2020-10-14 11:05
I was checking some sentry issues from times when this was happening and found some relevant logs, the `git config --get` commands failed in worker in `/src` dir:

```
subprocess      git config --get user.name
subprocess.cwd: /src
```
```
rebasehelper.helpers.git_helper
Failed to get configured git user name, using 'rebase-helper'
```
```
subprocess      git config --get user.email
subprocess.cwd: /src
```
```
rebasehelper.helpers.git_helper
Failed to get configured git user email, using 'rebase-helper@localhost.local'
```
Tried to reproduce, but commands return correct values now, and I haven't found any occurrences of this error since 21th September, so I propose to close this issue and possibly revisit it if it happens in future.

**Comment by TomasTomecek** [comment] 2020-10-14 13:55
@lbarcziova oh my, what a ~~cluster-f...~~ mess; thanks for such a thorough investigation

since we are now confident that the way %changelog user is being populed is via `git config --get`, would it make sense to have a test case which would run in the worker deployed in p-s and check that we are getting the value from the git-config-get we are expecting?

**Comment by lachmanfrantisek** [comment] 2020-11-03 07:37
@lbarcziova this is solved by your PR, isn't it?

btw, Thanks for your deep investigation!

**Comment by lbarcziova** [comment] 2020-11-03 09:05
> @lbarcziova this is solved(=not occurring anymore and a test added) by your PR, isn't it?

Yes, closing.

**Closed by lbarcziova** 2020-11-03 09:05 UTC
Labels: bug
