### ISSUE TITLE
Some tests require network connection

### ISSUE THREAD

**Issue by FrNecas** [packit/packit-service#1783] opened 2022-11-28 16:31 UTC
This occurred during the copr outage, apparently `test_submit_copr_build` queries the copr backend for some data under the hood (the tests failed due to timeout during the outage). I haven't been able to quickly find the root cause yet  (and I do not want to get too sidetracked) but we are probably missing some mocks, or we could use requre. Should be reproducible by disconnecting from the network and running the test suite.

```
tests/unit/test_copr_build.py:2697:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
packit_service/worker/helpers/build/copr_build.py:585: in submit_copr_build
    raise ex
        buildopts  = {}
        owner      = ''
        script     = None
        self       = <packit_service.worker.helpers.build.copr_build.CoprBuildJobHelper object at 0x7f899be98d90>
packit_service/worker/helpers/build/copr_build.py:528: in submit_copr_build
    "chroots": list(self.build_targets),
        buildopts  = {}
        owner      = ''
        script     = None
        self       = <packit_service.worker.helpers.build.copr_build.CoprBuildJobHelper object at 0x7f899be98d90>
packit_service/worker/helpers/build/build_helper.py:174: in build_targets
    return self.build_targets_all
        self       = <packit_service.worker.helpers.build.copr_build.CoprBuildJobHelper object at 0x7f899be98d90>
packit_service/worker/helpers/build/copr_build.py:208: in build_targets_all
    return get_valid_build_targets(*self.configured_build_targets, default=None)
        self       = <packit_service.worker.helpers.build.copr_build.CoprBuildJobHelper object at 0x7f899be98d90>
/usr/lib/python3.10/site-packages/packit/config/aliases.py:136: in get_valid_build_targets
    copr_chroots = CoprHelper.get_available_chroots()
        build_targets = {'fedora-31-x86_64', 'fedora-32-x86_64'}
        default    = None
        name       = ('fedora-stable',)
/usr/local/lib/python3.10/site-packages/cachetools/func.py:62: in wrapper
    v = func(*args, **kwargs)
        args       = ()
        cache      = TTLCache({}, maxsize=1, currsize=0)
        func       = <function CoprHelper.get_available_chroots at 0x7f89a1a36c20>
        hits       = 0
        k          = ()
        key        = <function hashkey at 0x7f89a2115510>
        kwargs     = {}
        lock       = <unlocked _thread.RLock object owner=0 count=0 at 0x7f89a1fb6580>
        misses     = 1
/usr/lib/python3.10/site-packages/packit/copr_helper.py:373: in get_available_chroots
    client.mock_chroot_proxy.get_list().keys(),
        client     = <copr.v3.client.Client object at 0x7f899be9b880>
/usr/lib/python3.10/site-packages/copr/v3/helpers.py:73: in wrapper
    result = func(*args, **kwargs)
```

**Comment by TomasTomecek** [comment] 2022-11-29 09:19
Very good point, we should mock these remote calls

**Comment by TomasTomecek** [comment] 2022-12-06 09:47
Duplicate of #1491

**Closed by TomasTomecek** 2022-12-06 09:47 UTC
Labels: testing
