### ISSUE TITLE
Leftover PVCs in sandbox namespace consume all storage quota

### ISSUE THREAD

**Issue by dhodovsk** [packit/packit-service#409] opened 2020-02-17 08:25 UTC
Some calls fail with `forbidden`:
```
Preparing of the upstream to the SRPM build failed: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-store', 'Content-Type': 'application/json', 'Date': 'Mon, 17 Feb 2020 08:20:43 GMT', 'Content-Length': '465'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"persistentvolumeclaims \"sandcastle--sandcastle-20200217-082043122119-pvc\" is forbidden: exceeded quota: 74746f6d6563656b407265646861742e636f6d-noncompute, requested: requests.storage=1Gi, used: requests.storage=23Gi, limited: requests.storage=23Gi","reason":"Forbidden","details":{"name":"sandcastle--sandcastle-20200217-082043122119-pvc","kind":"persistentvolumeclaims"},"code":403}
```

Examples:
https://github.com/packit-service/hello-world/pull/78
https://github.com/packit-service/hello-world/pull/79
https://github.com/dhodovsk/udisks/pull/1

**Comment by dhodovsk** [comment] 2020-02-17 08:53
https://sentry.io/share/issue/93f749445a7346c385f53ebcd67290d0/

**Comment by jpopelka** [comment] 2020-02-17 08:55
I've deleted some unused pods/volumes, so this should be "fixed" now.

**Comment by csomh** [comment] 2020-02-21 08:56
@dhodovsk is there anything left to do on this issue? Could it be closed?

**Comment by dhodovsk** [comment] 2020-02-24 09:54
The thing that remains is prevention. How can we ensure this won't happen in the future?

**Comment by dhodovsk** [comment] 2020-02-26 12:56
We can't. Today's forced packit overload caused a lot of the `exceeded quota` issues:
 - https://github.com/dhodovsk/ansible-bender/pull/1
 - https://github.com/dhodovsk/jose/pull/1
 - https://github.com/dhodovsk/python-nitrate/pull/1
 - https://github.com/dhodovsk/python-meh/pull/1
 - https://github.com/dhodovsk/libica/pull/1
 - https://github.com/dhodovsk/jansi-native/pull/1
 - https://github.com/dhodovsk/initial-setup/pull/1
 - https://github.com/dhodovsk/numactl/pull/1
 - https://github.com/dhodovsk/pycharm-community-edition/pull/1
 - https://github.com/dhodovsk/python-simpleline/pull/2
 - https://github.com/dhodovsk/node-rpm/pull/1
 - https://github.com/dhodovsk/conman/pull/1
 - https://github.com/dhodovsk/dasbus/pull/1
 - https://github.com/dhodovsk/sos/pull/1
 - https://github.com/dhodovsk/requests/pull/1
 - https://github.com/dhodovsk/avocado/pull/1
 - https://github.com/dhodovsk/cronie/pull/1
 - https://github.com/dhodovsk/flexmock/pull/1
 - https://github.com/dhodovsk/langtable/pull/1
 - https://github.com/dhodovsk/bubblewrap/pull/1

**Comment by TomasTomecek** [comment] 2020-02-27 07:18
We should probably set up a k8s job to delete lingering PVs in packit-{prod,stg} namespaces.

Or fix the original problem in p-s/sandcastle, but I wasn't able to to track that one down.

**Comment by TomasTomecek** [comment] 2020-03-11 15:21
yeah, we are running low on mem once again

**Comment by csomh** [comment] 2020-06-08 10:04
Petr reached out today, that this [is happening](https://github.com/psss/tmt/pull/278). Many PVCs were days old in the prod sandbox namespace.

**Comment by TomasTomecek** [comment] 2020-08-10 06:49
We have a cronjob to clear these - the core problem is not solved, but the issue is taken care of. Closing, feel free to reopen if you wanna track this still.

**Closed by TomasTomecek** 2020-08-10 06:49 UTC
Labels: bug
