### ISSUE TITLE
packit.stg did not accept our result update

### ISSUE THREAD

**Issue by thrix** [packit/packit-service#1028] opened 2021-03-24 11:36 UTC
Franta Sumsal reported an issue about:

https://github.com/systemd-ci-incubator/systemd/pull/11

Saying

```
packit-stg/testing-farm-fedora-rawhide-x86_64 Pending — Tests have been submitted ...
```

But according to our records we sent and update after our testing was completed with an error state:

```
[11:19:38] [D] https://stg.packit.dev:443 "POST /api/testing-farm/results HTTP/1.1" 200 24
[11:19:38] [D] response content:
---v---v---v---v---v---
"Test results accepted"
---v---v---v---v---v---
```

Please investigate ... I know this is staging ... but it should still werk

**Comment by lachmanfrantisek** [comment] 2021-03-24 12:01
Hi @thrix,

that's weird -- It works well in our testing PR (https://github.com/packit/hello-world/pull/196#issuecomment-805468814).

But I've merged some bigger changes in our database schema so maybe a related problem to that. I am not working today so will take a look tomorrow. Sorry about that.

**Comment by lbarcziova** [comment] 2021-03-24 12:42
I found a corresponding [issue](https://sentry.io/organizations/red-hat-0p/issues/1809076278/?project=1767823&query=is%3Aunresolved) in Sentry. We did process the result, but there was raised an exception when we tried to get file from `master` branch:
```
GithubException: 404 {"message": "No commit found for the ref master", "documentation_url": "https://docs.github.com/v3/repos/contents/"}
```
 so I assume we wrongly parse the `ref`.

**Comment by jpopelka** [comment] 2021-03-24 14:52
I investigated that problem yesterday and found no indicator in the logs about why the check was not updated.

Yes, I also spotted the Sentry issue and initially thought it's the cause, but after that, I realized this issue occurs quite often and it's probably because we do some URL swapping magic (TM) [before we submit tests to TF](https://github.com/packit/packit-service/blob/9bc0408cb3953777c75fca975178d60999e64106/packit_service/worker/testing_farm.py#L316) and [after we get the results back](https://github.com/packit/packit-service/blob/9bc0408cb3953777c75fca975178d60999e64106/packit_service/worker/parser.py#L824). So at the moment I think it was not the cause of the not updated check, but I'm not completely sure.

**Comment by lbarcziova** [comment] 2021-03-24 15:19
Yes, it happens quite often, not only for this type of issue but for this PR I think it happened all the time or am I wrong?

What I thought was that similarly as [here](https://github.com/packit/packit-service/blob/9bc0408cb3953777c75fca975178d60999e64106/packit_service/worker/parser.py#L805)  we should use the value for `ref` from DB , since the `commit_sha` there is set [correctly](https://dashboard.stg.packit.dev/results/testing-farm/5483) (whereas from the `nested_get(event, "test", "fmf", "ref")` we get `master` which is wrong)

**Comment by jpopelka** [comment] 2021-03-24 15:32
Oh yes, you're right!

Do you want to create a PR? I think we just need to move the
```python
            if tft_test_run:
                ref = tft_test_run.commit_sha
```
outside of the `if project_url == TESTING_FARM_INSTALLABILITY_TEST_URL:`

**Closed** 2021-03-24 16:52 UTC
