### ISSUE TITLE
Declares running tests as failed

### ISSUE THREAD

**Issue by martinpitt** [packit/packit-service#2216] opened 2023-10-06 08:09 UTC
### What happened? What is the problem?

In https://github.com/cockpit-project/cockpit/pull/19448 and other PRs today I've seen packit tests marked as failure:

![image](https://github.com/packit/packit-service/assets/200109/5161bcd1-df2e-4d50-9c9e-f44d23b6bdb8)

while they are still running. At the time of writing, https://artifacts.dev.testing-farm.io/692a5d85-93a3-4b57-82e9-291a3211d32e/ is running happily, with two plans passed, and the third one still in progress.

### What did you expect to happen?

Yellow "in progress" status.

### Example URL(s)

https://github.com/cockpit-project/cockpit/pull/19448

### What is the impacted category (job)?

Testing Farm tests

### Workaround

- [X] There is an existing workaround that can be used until this issue is fixed.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by martinpitt** [comment] 2023-10-06 08:11
And now https://artifacts.dev.testing-farm.io/692a5d85-93a3-4b57-82e9-291a3211d32e/ actually finished, but the PR still shows it as failed. Something similar happened this morning in https://github.com/containers/podman/pull/20286 , where the test was notified for failure, but it actually passed.

**Comment by martinpitt** [comment] 2023-10-06 08:18
https://github.com/cockpit-project/cockpit/pull/19401 is another case -- https://artifacts.dev.testing-farm.io/c0e0f78d-94f6-4d1f-9a28-04b1f143d7f0/ is currently running:

```
+-----------------------------------------------------+---------+---------+-----------+------------------------------------+--------------------------------------+----------+
| SE                                                  | Stage   | State   | Result    | Environment                        | Guest                                | Runner   |
|-----------------------------------------------------+---------+---------+-----------+------------------------------------+--------------------------------------+----------|
| CentOS-Stream-9-aarch64:aarch64:/plans/all/basic    | RUNNING | OK      | UNDEFINED | aarch64 CentOS-Stream-9-aarch64 S- | aarch64 CentOS-Stream-9-aarch64 S-   | tmt      |
|                                                     |         |         |           |                                    | bb9e7e08-1220-4390-b21c-cf241c7aa7e1 |          |
| CentOS-Stream-9-aarch64:aarch64:/plans/all/network  | RUNNING | OK      | UNDEFINED | aarch64 CentOS-Stream-9-aarch64 S- | aarch64 CentOS-Stream-9-aarch64 S-   | tmt      |
|                                                     |         |         |           |                                    | dad67055-bedc-47eb-a80c-02986196d8cc |          |
| CentOS-Stream-9-aarch64:aarch64:/plans/all/optional | RUNNING | OK      | UNDEFINED | aarch64 CentOS-Stream-9-aarch64 S- | aarch64 CentOS-Stream-9-aarch64 S-   | tmt      |
|                                                     |         |         |           |                                    | 267fc90b-ce4e-4189-a391-80c6f5e0f1cb |          |
+-----------------------------------------------------+---------+---------+-----------+------------------------------------+--------------------------------------+----------+[0m
[32m[07:29:45] [+] [worker_1] [CentOS-Stream-9-aarch64:aarch64:/plans/all/optional] starting tests execution[0m
[32m[07:29:45] [+] [worker_1] [CentOS-Stream-9-aarch64:aarch64:/plans/all/optional] TMT logs are in https://artifacts.dev.testing-farm.io/c0e0f78d-94f6-4d1f-9a28-04b1f143d7f0/work-optionaldm8xifid/tmt-run.log[0m
[32m[07:29:45] [+] [worker_1] [test-schedule-tmt-connect] running in /var/ARTIFACTS/git-4edda8d87519afeb1530110ec75af99e196cd087ygbslbh0[0m
```

and the packit status page https://dashboard.packit.dev/results/testing-farm/283380 shows it as unknown:

![image](https://github.com/packit/packit-service/assets/200109/843d2605-e969-475e-9ad7-a664063364b5)

But the PR shows it as failure:

![image](https://github.com/packit/packit-service/assets/200109/0be38f9d-4b99-4f52-8a19-deab5674dfeb)

We look at a *lot* of TF tests, and this has never happened until yesterday evening/last night. Did something significant change since then?

**Comment by lbarcziova** [comment] 2023-10-06 08:38
Thank @martinpitt for all the details! On our side, the related code was not changed and I think TF has not done the planned release yet (ping @thrix).

The problem is the result of the affected TF runs (e.g. the currently in progress one https://api.dev.testing-farm.io/v0.1/requests/c0e0f78d-94f6-4d1f-9a28-04b1f143d7f0 )  is`unknown` that is then reported as `failed`. I need to find out whether this is something that has changed on TF side or what could be the issue. Going to investigate further.

**Comment by lbarcziova** [comment] 2023-10-06 11:10
Confirmed that the problem is on the TF side, tracking issue: https://gitlab.com/testing-farm/general/-/issues/71

**Comment by martinpitt** [comment] 2023-10-06 12:16
Thanks @lbarcziova ! I subscribed to that TF issue, feel free to close this one.

**Comment by lbarcziova** [comment] 2023-10-09 06:40
@martinpitt in #2217 there were introduced few changes that should improve handling of the scenario from Friday, therefore closing this one. Thanks once again for reporting!

**Closed by lbarcziova** 2023-10-09 06:40 UTC
Labels: kind/bug

**Comment by martinpitt** [comment] 2023-10-09 06:50
Thanks @lbarcziova !
