### ISSUE TITLE
pull_from_upstream + changelog-entry action = nope, still got upstream commit titles

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#2125] opened 2023-07-24 14:53 UTC
### What happened? What is the problem?

I set up a changelog-entry action for my package:

https://src.fedoraproject.org/rpms/python-docker/c/dc64b29ab79824525f0bd12fe986a0a73e96fb84?branch=rawhide

Because I wanted the plain `new upstream release $version` changelog entries

But I was still getting the upstream commit messages from the last tag

https://src.fedoraproject.org/rpms/python-docker/pull-request/42#request_diff

What am I missing?

### What is the impacted category (job)?

Fedora release automation

**Comment by TomasTomecek** [comment] 2023-07-25 07:26
I suspect the changelog action is not run: https://dashboard.packit.dev/results/pull-from-upstream/3004

**Comment by lbarcziova** [comment] 2023-08-07 08:38
Was curious so I checked the logs:

```
Package config before loading:
{
    "specfile_path": "python-docker.spec",
    "downstream_package_name": "python-docker",
    "upstream_project_url": "https://github.com/docker/docker-py",
    "actions": {
        "create-archive": [
            "python3 setup.py sdist --dist-dir .",
            "ls -1 ./*.tar.gz"
        ],
        "get-current-version": "python3 setup.py --version"
    },
    "issue_repository": "https://github.com/TomasTomecek/docker-py",
    "jobs": [
        {
            "job": "pull_from_upstream",
            "trigger": "release",
            "dist_git_branches": [
                "fedora-all",
                "epel-8",
                "epel-9"
            ]
        }
    ]
}
```

and

`Found a config file '.packit.yaml' on ref '87d8767f73c1d64a3121d2eb2f9c1aef1dd13528' of the 'rpms/python-docker' repository.`

So the version of the configuration we obtained did not include that action at that moment ([looks](https://src.fedoraproject.org/api/0/rpms/python-docker/c/87d8767f73c1d64a3121d2eb2f9c1aef1dd13528/info) like the config was taken from the target branch of the PR with the comment).

I would therefore close this as a duplicate of #2115 if you are not against.

**Comment by TomasTomecek** [comment] 2023-08-07 12:29
agreed! thank you for investigating

**Closed** 2023-08-07 12:29 UTC
Labels: kind/bug, area/fedora, complexity/single-task, impact/low, gain/low
