### ISSUE TITLE
RFE: Notify on failure + tag github user(s) along with custom failure message

### ISSUE THREAD

**Issue by lsm5** [packit/packit-service#1911] opened 2023-02-14 11:52 UTC
As a packit-service user responsible for monitoring the packit jobs on the containers' team repos, I'd like to be notified whenever there's a packit failure on any PR, preferably via tagging my github id and a customizable message.

The current packit configuration docs only mention notification on build success, nothing for failure.

/cc @evgeni

**Comment by lsm5** [comment] 2023-02-14 12:03
in case a custom copr project is used for builds, another option might be to tag the FAS accounts listed with builder perms on the copr.

**Comment by lachmanfrantisek** [comment] 2023-02-16 12:28
@lsm5 Thanks for creating the issue!

The outcome of today's team discussion:
* use a comment for that (other possibilities have been considered)
* provide a config option to set the content of the comment (and allow templating as a follow-up if needed)
  * if set, this feature is enabled
* make sure we don't spam too much

**Comment by lsm5** [comment] 2023-02-16 13:20
> * use a comment for that (other possibilities have been considered)

github comment is nice!

> * make sure we don't spam too much

can this be made configurable as well? Remind every x hours / days if no human response and / or still failing as set in the config?

Thank you!!

**Comment by lachmanfrantisek** [comment] 2023-02-17 12:11
> can this be made configurable as well? Remind every x hours / days if no human response and / or still failing as set in the config?

To be really honest, we can't easily do any scheduled work without significant changes to Packit's architecture... (Packit now works on an event-based architecture.)

But I've searched through the GitHub marketplace and we might be able to combine Packit with some other GitHub action/app to do this. E.g. Packit can create a comment that will be picked by another action like [this one](https://github.com/marketplace/actions/create-reminder) to create reminders...

Sadly, I wasn't able to find anything generic capable of the whole workflow (because this might be handy not only for Packit statuses..;)

**Comment by martinpitt** [comment] 2023-08-03 17:58
Adding a "me too". I am currently starting to establish some cross-project testing, see https://cockpit-project.org/blog/tmt-cross-project-testing.html . It doesn't scale well to tell these "other projects" to notify a set of people on failures, as people are notoriously bad at remembering to do that, and whom to contact.

This could possibly be modelled as an `on: status` GitHub workflow, but that would be *hideously* expensive. I think packit is in a much better position to do that -- it already sends an API request for updating the yellow to red or green -- that would be the correct place to also post a comment with such a pre-configured failure message. The most interesting part would be to @ the maintainers.

**Comment by lachmanfrantisek** [comment] 2023-08-15 15:58
@martinpitt thanks for describing your use case! Since also @evgeni mentioned this one to me yesterday as important for Forman projects, I am prioritising the card...;)

This can really bring Packit to projects independent of Fedora/Packit.

**Comment by martinpitt** [comment] 2023-09-12 06:36
@lachmanfrantisek , @lbarcziova: We recently had a [nice success story](https://github.com/containers/podman/pull/19888#issuecomment-1711548343) around that -- a podman PR broke some functionality, our reverse dependency tests caught it, it was debugged in an hour, and eventually the PR landed without the regression.

But I only found that because I regularly poll the podman PRs and just got lucky. As this isn't very reliable, I wanted to ask: Do you have a coarse time frame for this notification feature? I can probably write a hackjob GH workflow that does that polling in half a day or so, but I wonder if it's worth it.

Thanks!

**Comment by lbarcziova** [comment] 2023-09-12 06:38
@martinpitt happy to hear that!

Just yesterday I started to work on this feature, I believe is will be in production next Tuesday :)

**Comment by martinpitt** [comment] 2023-09-12 06:39
@lbarcziova that sounds amazing, good luck! I'm happy to be a test guinea pig, of course. (However, I'll be on PTO this Thu/Fri, and possibly on Mon)

**Closed** 2023-09-13 06:49 UTC
Labels: kind/feature, complexity/single-task, impact/low, area/general, gain/high, area/config
