### ISSUE TITLE
packit/rpm-build - Only collaborators can trigger Packit-as-a-Service

### ISSUE THREAD

**Issue by yarda** [packit/packit-service#250] opened 2019-11-18 11:45 UTC
We want all PRs to trigger the rebuild. Why we are receiving this error on PRs from non-collaborators?
`packit/rpm-build - Only collaborators can trigger Packit-as-a-Service`

I have to trigger the rebuild manually. It happened e.g. in:
 https://github.com/redhat-performance/tuned/pull/210

**Comment by TomasTomecek** [comment] 2019-11-21 11:25
Design decision:
* Utilize check from https://github.com/packit-service/packit-service/pull/237 whether p-s is allowed to be used
* If a PR by a non-contributor is created: the upstream project needs to trigger p-s for the first time
  * Create an issue in the notification repo to whitelist the person
* Once the check is green, keep on buildin'
* Whitelist checking: check if the person is whitelisted, not just the namespace of the repo

**Comment by lachmanfrantisek** [comment] 2019-12-03 11:10
Output from the today's architecture meeting:

- `\packit whitelist` to whitelist author of the PR in the PR/project
    - more transparent, allows removing from the project whitelist
    - onetime action needed from the maintainers

**Comment by lachmanfrantisek** [comment] 2020-05-18 13:36
I am adding EPIC so we don't receive messages from the stale bot. (Multiple things needs to be done here.)

**Comment by lachmanfrantisek** [comment] 2020-11-24 15:47
The issue is here for some time so it's probably a time to make some conclusion. There were multiple solutions mentioned already:

- Globally whitelist users -- user needs to be approved on our side for the first time.
- Comment of the allowed user will unlock the PR for forever.
- Provide some config option and/or comment command to enable the user across the project.
 
Do we have anything else? Which one(s) do we prefer?  (The solutions can be combined...)

**Comment by TomasTomecek** [comment] 2020-11-25 11:31
> The issue is here for some time so it's probably a time to make some conclusion. There were multiple solutions mentioned already:
> 
>     * Globally whitelist users -- user needs to be approved on our side for the first time.

I really like this one - once a user is approved we can trust the person.

>     * Comment of the allowed user will unlock the PR for forever.

Sounds good as well, though you'd need to store this in DB probably which may be complicated to implement.

>     * Provide some config option and/or comment command to enable the user across the project.

Can be a great way in combination with 1)

**Comment by lachmanfrantisek** [comment] 2021-01-19 10:52
Some update on this topic. Copr [has reached](https://github.com/packit/packit-service/issues/920) to us that we don't need to require write access for the pull-request authors to start the build.

I am going to close this issue in favour of #920 since it contains the more up-to-date info and contains the solution for this problem.

The implementation is not hard and we want to start working on this soon.

**Closed by lachmanfrantisek** 2021-01-19 10:52 UTC
Labels: feature, triaged, user-experience
