### ISSUE TITLE
Frequent-ish timeouts when scheduling jobs

### ISSUE THREAD

**Issue by mrc0mmand** [packit/packit-service#1529] opened 2022-05-30 12:24 UTC
Hello!

For the past several weeks I've been noticing a increasing amount of timeout-related messages when creating/updating PRs in the systemd repository:

![image](https://user-images.githubusercontent.com/679338/170990960-f9605d7f-6c73-407d-a81b-1db72b9ed1b4.png)

https://github.com/systemd/systemd/pull/23555/checks?check_run_id=6654572957

Full message:
*Submit of the build failed: Gateway Timeout Consider using pagination for large queries.*

Resolving this takes several retries (interleaved with some waits in-between). Is there anything that can be done on our side to mitigate this?

**Comment by lachmanfrantisek** [comment] 2022-05-30 13:10
Hi @mrc0mmand !

I am sorry about that. This was caused by Copr and should be fixed now. In all cases, Packit should handle the retries for you -- I am going to close this issue in favour of #927 and update&prioritise that one.

Thanks for reaching out to us!

**Closed by lachmanfrantisek** 2022-05-30 13:10 UTC
